on:
  push:
    paths-ignore:
      - "README.md"
      - "changelog.md"
      - "CommunityContributions/**"
    branches:
      - master

  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Run Continuous Integration
        shell: pwsh
        run: |
          Install-Module -Name PowerShellAI.Functions -Force
          
          cd ./__tests__
          Invoke-Pester -Output Detailed
